### PR TITLE
examples: migrate to vite

### PR DESCRIPTION
**Pull request by dai-shi**
we need standalone tsconfig files.

Also migrate from CRA to Vite, which is modern.

close #5

### CODE REVIEW

**Comment by dai-shi** [comment]
Testing with https://stackblitz.com/github/dai-shi/use-signals/tree/migrate-to-stackblitz/examples/01_counter, and got this:
```
Error in src/index.tsx (1:1)
Option 'bundler' can only be used when 'module' is set to 'preserve' or to 'es2015' or later.
```

**Comment by dai-shi** [comment]
https://codesandbox.io/p/sandbox/github/dai-shi/use-signals/tree/migrate-to-stackblitz/examples/01_counter works, but TS error is shown.

image

**Comment by dai-shi** [comment]
https://livecodes.io/?x=https://github.com/dai-shi/use-signals/tree/migrate-to-stackblitz/examples/01_counter/src works flawlessly. (except that it shows empty HTML tab first.) cc @hatemhosny

I actually wish https://livecodes.io/?x=https://github.com/dai-shi/use-signals/tree/migrate-to-stackblitz/examples/01_counter would work. 😄

**Comment by hatemhosny** [comment]
You can add the query param [`activeEditor=script`](https://livecodes.io/docs/configuration/configuration-object#activeeditor)

https://livecodes.io/?x=https://github.com/dai-shi/use-signals/tree/migrate-to-stackblitz/examples/01_counter/src&activeEditor=script

Also see [file selection](https://livecodes.io/docs/features/import#file-selection).

**Comment by hatemhosny** [comment]
> https://livecodes.io/?x=https://github.com/dai-shi/use-signals/tree/migrate-to-stackblitz/examples/01_counter/src works flawlessly. (except that it shows empty HTML tab first.) 
> 

You are right. It should not select an empty editor by default. 
I will try to improve that. 
Also, some improvements can be made in the docs.
Thank you.

**Comment by hatemhosny** [comment]
And if you want to import 1 file, you can just use its url

https://livecodes.io/?x=https://github.com/dai-shi/use-signals/blob/migrate-to-stackblitz/examples/01_counter/src/app.tsx

**Comment by dai-shi** [comment]
> https://livecodes.io/?x=https://github.com/dai-shi/use-signals/blob/migrate-to-stackblitz/examples/01_counter/src/app.tsx

That's reasonable as LiveCodes only works with one tsx file anyway, right?

**Comment by dai-shi** [comment]
https://stackblitz.com/github/dai-shi/use-signals/tree/migrate-to-stackblitz/examples/02_jsx works fine.

https://codesandbox.io/p/sandbox/github/dai-shi/use-signals/tree/migrate-to-stackblitz/examples/02_jsx works fine.

https://livecodes.io/?x=https://github.com/dai-shi/use-signals/blob/migrate-to-stackblitz/examples/02_jsx/src/app.tsx works fine.

**Review by dai-shi — COMMENTED** [review]
Not sure how acceptable it is with the community standard, but I like how it is.

**Pull request merged**
